

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow2(object):
    def setupUi2(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(339, 565)
        MainWindow.setMinimumSize(QtCore.QSize(339, 565))
        MainWindow.setMaximumSize(QtCore.QSize(339, 565))
        MainWindow.setSizeIncrement(QtCore.QSize(0, 1))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTipDuration(-1)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 341, 531))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_buttons = QtWidgets.QFrame(self.frame)
        self.frame_buttons.setGeometry(QtCore.QRect(10, 120, 321, 421))
        self.frame_buttons.setStyleSheet("")
        self.frame_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_buttons.setObjectName("frame_buttons")
        self.point = QtWidgets.QPushButton(self.frame_buttons)
        self.point.setGeometry(QtCore.QRect(140, 350, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.point.setFont(font)
        self.point.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);border-radius: 30px;")
        self.point.setObjectName("point")
        self.three = QtWidgets.QPushButton(self.frame_buttons)
        self.three.setGeometry(QtCore.QRect(140, 280, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.three.setFont(font)
        self.three.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);border-radius: 30px;")
        self.three.setObjectName("three")
        self.zero = QtWidgets.QPushButton(self.frame_buttons)
        self.zero.setGeometry(QtCore.QRect(70, 350, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.zero.setFont(font)
        self.zero.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);border-radius: 30px;")
        self.zero.setObjectName("zero")
        self.two = QtWidgets.QPushButton(self.frame_buttons)
        self.two.setGeometry(QtCore.QRect(70, 280, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.two.setFont(font)
        self.two.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);;border-radius: 30px;")
        self.two.setObjectName("two")
        self.eight = QtWidgets.QPushButton(self.frame_buttons)
        self.eight.setGeometry(QtCore.QRect(70, 140, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.eight.setFont(font)
        self.eight.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);border-radius: 30px;")
        self.eight.setObjectName("eight")
        self.back = QtWidgets.QPushButton(self.frame_buttons)
        self.back.setGeometry(QtCore.QRect(210, 0, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.back.setFont(font)
        self.back.setStyleSheet("background-color: rgb(255, 216, 97);\n"
"color: rgb(120, 120, 120);\n"
"border-radius: 30px;")
        self.back.setObjectName("back")
        self.five = QtWidgets.QPushButton(self.frame_buttons)
        self.five.setGeometry(QtCore.QRect(70, 210, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.five.setFont(font)
        self.five.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);border-radius: 30px;")
        self.five.setObjectName("five")
        self.seven = QtWidgets.QPushButton(self.frame_buttons)
        self.seven.setGeometry(QtCore.QRect(0, 140, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.seven.setFont(font)
        self.seven.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);\n"
"border-radius: 30px;")
        self.seven.setObjectName("seven")
        self.plus_minus = QtWidgets.QPushButton(self.frame_buttons)
        self.plus_minus.setGeometry(QtCore.QRect(0, 350, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.plus_minus.setFont(font)
        self.plus_minus.setStyleSheet("border-radius: 30px;color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);")
        self.plus_minus.setObjectName("plus_minus")
        self.multiply = QtWidgets.QPushButton(self.frame_buttons)
        self.multiply.setGeometry(QtCore.QRect(210, 140, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.multiply.setFont(font)
        self.multiply.setStyleSheet("background-color: rgb(255, 216, 97);\n"
"color: rgb(120, 120, 120);border-radius: 30px;")
        self.multiply.setObjectName("multiply")
        self.x_square = QtWidgets.QPushButton(self.frame_buttons)
        self.x_square.setGeometry(QtCore.QRect(70, 70, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.x_square.setFont(font)
        self.x_square.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);border-radius: 30px;")
        self.x_square.setObjectName("x_square")
        self.divide = QtWidgets.QPushButton(self.frame_buttons)
        self.divide.setGeometry(QtCore.QRect(210, 70, 111, 61))
        self.divide.setMinimumSize(QtCore.QSize(111, 61))
        self.divide.setMaximumSize(QtCore.QSize(111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.divide.setFont(font)
        self.divide.setStyleSheet("background-color: rgb(255, 216, 97);\n"
"color: rgb(120, 120, 120);\n"
"border-radius: 30px;")
        self.divide.setObjectName("divide")
        self.root = QtWidgets.QPushButton(self.frame_buttons)
        self.root.setGeometry(QtCore.QRect(140, 70, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.root.setFont(font)
        self.root.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);border-radius: 30px;")
        self.root.setObjectName("root")
        self.per = QtWidgets.QPushButton(self.frame_buttons)
        self.per.setGeometry(QtCore.QRect(0, 0, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.per.setFont(font)
        self.per.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(232, 232, 232);\n"
"border-radius: 30px;")
        self.per.setObjectName("per")
        self.six = QtWidgets.QPushButton(self.frame_buttons)
        self.six.setGeometry(QtCore.QRect(140, 210, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.six.setFont(font)
        self.six.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);border-radius: 30px;")
        self.six.setObjectName("six")
        self.four = QtWidgets.QPushButton(self.frame_buttons)
        self.four.setGeometry(QtCore.QRect(0, 210, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.four.setFont(font)
        self.four.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);border-radius: 30px;")
        self.four.setObjectName("four")
        self.plus = QtWidgets.QPushButton(self.frame_buttons)
        self.plus.setGeometry(QtCore.QRect(210, 280, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.plus.setFont(font)
        self.plus.setStyleSheet("background-color: rgb(255, 216, 97);\n"
"color: rgb(120, 120, 120);border-radius: 30px;")
        self.plus.setObjectName("plus")
        self.equal = QtWidgets.QPushButton(self.frame_buttons)
        self.equal.setGeometry(QtCore.QRect(210, 350, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.equal.setFont(font)
        self.equal.setStyleSheet("background-color: rgb(255, 216, 97);\n"
"color: rgb(120, 120, 120);border-radius: 30px;")
        self.equal.setObjectName("equal")
        self.one_by_x = QtWidgets.QPushButton(self.frame_buttons)
        self.one_by_x.setGeometry(QtCore.QRect(0, 70, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.one_by_x.setFont(font)
        self.one_by_x.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);\n"
"border-radius: 30px;")
        self.one_by_x.setObjectName("one_by_x")
        self.nine = QtWidgets.QPushButton(self.frame_buttons)
        self.nine.setGeometry(QtCore.QRect(140, 140, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.nine.setFont(font)
        self.nine.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);border-radius: 30px;")
        self.nine.setObjectName("nine")
        self.minus = QtWidgets.QPushButton(self.frame_buttons)
        self.minus.setGeometry(QtCore.QRect(210, 210, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.minus.setFont(font)
        self.minus.setStyleSheet("background-color: rgb(255, 216, 97);\n"
"color: rgb(120, 120, 120);border-radius: 30px;")
        self.minus.setObjectName("minus")
        self.one = QtWidgets.QPushButton(self.frame_buttons)
        self.one.setGeometry(QtCore.QRect(0, 280, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.one.setFont(font)
        self.one.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);border-radius: 30px;")
        self.one.setObjectName("one")
        self.clear = QtWidgets.QPushButton(self.frame_buttons)
        self.clear.setGeometry(QtCore.QRect(140, 0, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.clear.setFont(font)
        self.clear.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(232, 232, 232);\n"
"border-radius: 30px;")
        self.clear.setObjectName("clear")
        self.ce = QtWidgets.QPushButton(self.frame_buttons)
        self.ce.setGeometry(QtCore.QRect(70, 0, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ce.setFont(font)
        self.ce.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(232, 232, 232);\n"
"border-radius: 30px;")
        self.ce.setObjectName("ce")
        self.frame_calculations_display = QtWidgets.QFrame(self.frame)
        self.frame_calculations_display.setGeometry(QtCore.QRect(10, 40, 321, 71))
        self.frame_calculations_display.setStyleSheet("")
        self.frame_calculations_display.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_calculations_display.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_calculations_display.setObjectName("frame_calculations_display")
        self.label_2 = QtWidgets.QLabel(self.frame_calculations_display)
        self.label_2.setGeometry(QtCore.QRect(0, 30, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setStyleSheet("color: rgb(117, 117, 117);")

        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_calculations_display)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 311, 20))
        self.label_3.setMaximumSize(QtCore.QSize(100000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setStyleSheet("color: rgb(117, 117, 117);")

        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 10, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(117, 117, 117);")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 339, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuOption = QtWidgets.QMenu(self.menuBar)
        self.menuOption.setStyleSheet("")
        self.menuOption.setTitle("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../images/text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuOption.setIcon(icon1)
        self.menuOption.setObjectName("menuOption")
        self.menuCalculator = QtWidgets.QMenu(self.menuOption)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../images/calculator(3).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuCalculator.setIcon(icon2)
        self.menuCalculator.setObjectName("menuCalculator")
        self.menuConverter = QtWidgets.QMenu(self.menuOption)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../images/recycle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuConverter.setIcon(icon3)
        self.menuConverter.setObjectName("menuConverter")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)

        self.actionExit = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../images/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon4)
        self.actionExit.setObjectName("actionExit")
        self.actionStandard = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../images/calculator.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStandard.setIcon(icon5)
        self.actionStandard.setObjectName("actionStandard")
        self.actionScientific = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../images/microscope.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionScientific.setIcon(icon6)
        self.actionScientific.setObjectName("actionScientific")
        self.actionProgrammer = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../images/code.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionProgrammer.setIcon(icon7)
        self.actionProgrammer.setObjectName("actionProgrammer")
        self.actionDate_Calculation = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../images/calendar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDate_Calculation.setIcon(icon8)
        self.actionDate_Calculation.setObjectName("actionDate_Calculation")

        self.actionVolume = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../images/shapes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVolume.setIcon(icon10)
        self.actionVolume.setObjectName("actionVolume")
        self.actionLength = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../images/ruler.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLength.setIcon(icon11)
        self.actionLength.setObjectName("actionLength")
        self.actionWeight_and_Mass = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("../images/weighing-scale.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionWeight_and_Mass.setIcon(icon12)
        self.actionWeight_and_Mass.setObjectName("actionWeight_and_Mass")
        self.actionTemperature = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("../images/temperature.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTemperature.setIcon(icon13)
        self.actionTemperature.setObjectName("actionTemperature")
        self.actionEnergy = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("../images/fire.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEnergy.setIcon(icon14)
        self.actionEnergy.setObjectName("actionEnergy")
        self.actionArea = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("../images/area.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionArea.setIcon(icon15)
        self.actionArea.setObjectName("actionArea")
        self.actionSpeed = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("../images/fast.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSpeed.setIcon(icon16)
        self.actionSpeed.setObjectName("actionSpeed")
        self.actionTime = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("../images/clock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTime.setIcon(icon17)
        self.actionTime.setObjectName("actionTime")
        self.actionPower = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("../images/energy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPower.setIcon(icon18)
        self.actionPower.setObjectName("actionPower")
        self.actionData = QtWidgets.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("../images/statistics.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionData.setIcon(icon19)
        self.actionData.setObjectName("actionData")
        self.actionPressure = QtWidgets.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("../images/indicator.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPressure.setIcon(icon20)
        self.actionPressure.setObjectName("actionPressure")
        self.actionAngle = QtWidgets.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("../images/angle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAngle.setIcon(icon21)
        self.actionAngle.setObjectName("actionAngle")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionDark_ = QtWidgets.QAction(MainWindow)
        self.actionDark_.setObjectName("actionDark_")
        self.actionLight_ = QtWidgets.QAction(MainWindow)
        self.actionLight_.setObjectName("actionLight_")
        self.menuCalculator.addAction(self.actionStandard)
        self.menuCalculator.addAction(self.actionScientific)
        self.menuCalculator.addAction(self.actionProgrammer)
        self.menuCalculator.addAction(self.actionDate_Calculation)
        self.menuConverter.addAction(self.actionVolume)
        self.menuConverter.addAction(self.actionLength)
        self.menuConverter.addAction(self.actionWeight_and_Mass)
        self.menuConverter.addAction(self.actionTemperature)
        self.menuConverter.addAction(self.actionEnergy)
        self.menuConverter.addAction(self.actionArea)
        self.menuConverter.addAction(self.actionSpeed)
        self.menuConverter.addAction(self.actionTime)
        self.menuConverter.addAction(self.actionPower)
        self.menuConverter.addAction(self.actionData)
        self.menuConverter.addAction(self.actionPressure)
        self.menuConverter.addAction(self.actionAngle)
        self.menuOption.addAction(self.menuCalculator.menuAction())
        self.menuOption.addAction(self.menuConverter.menuAction())
        self.menuOption.addSeparator()
        self.menuOption.addAction(self.actionExit)
        self.menuBar.addAction(self.menuOption.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.point.setText(_translate("MainWindow", "."))
        self.three.setText(_translate("MainWindow", "3"))
        self.zero.setText(_translate("MainWindow", "0"))
        self.two.setText(_translate("MainWindow", "2"))
        self.eight.setText(_translate("MainWindow", "8"))
        self.back.setToolTip(_translate("MainWindow", "Remove/Back"))
        self.back.setText(_translate("MainWindow", "<"))
        self.five.setText(_translate("MainWindow", "5"))
        self.seven.setText(_translate("MainWindow", "7"))
        self.plus_minus.setText(_translate("MainWindow", "+/-"))
        self.multiply.setToolTip(_translate("MainWindow", "Multiply"))
        self.multiply.setText(_translate("MainWindow", "X"))
        self.x_square.setToolTip(_translate("MainWindow", "Square"))
        self.x_square.setText(_translate("MainWindow", "x²"))
        self.divide.setToolTip(_translate("MainWindow", "Divide"))
        self.divide.setText(_translate("MainWindow", "/"))
        self.root.setToolTip(_translate("MainWindow", "Square root"))
        self.root.setText(_translate("MainWindow", "²√x"))
        self.per.setText(_translate("MainWindow", "%"))
        self.six.setText(_translate("MainWindow", "6"))
        self.four.setText(_translate("MainWindow", "4"))
        self.plus.setToolTip(_translate("MainWindow", "Plus"))
        self.plus.setText(_translate("MainWindow", "+"))
        self.equal.setText(_translate("MainWindow", "="))
        self.one_by_x.setToolTip(_translate("MainWindow", "one by x"))
        self.one_by_x.setText(_translate("MainWindow", "1/x"))
        self.nine.setText(_translate("MainWindow", "9"))
        self.minus.setToolTip(_translate("MainWindow", "Subtract"))
        self.minus.setText(_translate("MainWindow", "-"))
        self.one.setText(_translate("MainWindow", "1"))
        self.clear.setToolTip(_translate("MainWindow", "Clear"))
        self.clear.setText(_translate("MainWindow", "C"))
        self.ce.setToolTip(_translate("MainWindow", "Clear recent calculation"))
        self.ce.setText(_translate("MainWindow", "CE"))
        self.label_2.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "Standard"))
        self.menuCalculator.setTitle(_translate("MainWindow", "Calculator"))
        self.menuConverter.setTitle(_translate("MainWindow", "Converter"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))

        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionStandard.setText(_translate("MainWindow", "Standard"))
        self.actionScientific.setText(_translate("MainWindow", "Scientific"))
        self.actionProgrammer.setText(_translate("MainWindow", "Programmer"))
        self.actionDate_Calculation.setText(_translate("MainWindow", "Date Calculation"))
        self.actionVolume.setText(_translate("MainWindow", "Volume"))
        self.actionLength.setText(_translate("MainWindow", "Length"))
        self.actionWeight_and_Mass.setText(_translate("MainWindow", "Weight and Mass"))
        self.actionTemperature.setText(_translate("MainWindow", "Temperature"))
        self.actionEnergy.setText(_translate("MainWindow", "Energy"))
        self.actionArea.setText(_translate("MainWindow", "Area"))
        self.actionSpeed.setText(_translate("MainWindow", "Speed"))
        self.actionTime.setText(_translate("MainWindow", "Time"))
        self.actionPower.setText(_translate("MainWindow", "Power"))
        self.actionData.setText(_translate("MainWindow", "Data"))
        self.actionPressure.setText(_translate("MainWindow", "Pressure"))
        self.actionAngle.setText(_translate("MainWindow", "Angle"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionDark_.setText(_translate("MainWindow", "Dark"))
        self.actionLight_.setText(_translate("MainWindow", "Light"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow2()
    ui.setupUi2(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
