# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designing/light_theme_programmer.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_Programmer(object):
    def setupUiProgrammer(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(339, 565)
        MainWindow.setMinimumSize(QtCore.QSize(339, 565))
        MainWindow.setMaximumSize(QtCore.QSize(339, 565))
        MainWindow.setSizeIncrement(QtCore.QSize(0, 1))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTipDuration(-1)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 341, 531))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_buttons = QtWidgets.QFrame(self.frame)
        self.frame_buttons.setGeometry(QtCore.QRect(10, 230, 321, 301))
        self.frame_buttons.setStyleSheet("")
        self.frame_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_buttons.setObjectName("frame_buttons")
        self.p_point = QtWidgets.QPushButton(self.frame_buttons)
        self.p_point.setGeometry(QtCore.QRect(180, 250, 47, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.p_point.setFont(font)
        self.p_point.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);\n"
"border-radius: 22px;")
        self.p_point.setObjectName("p_point")
        self.p_three = QtWidgets.QPushButton(self.frame_buttons)
        self.p_three.setGeometry(QtCore.QRect(180, 200, 47, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.p_three.setFont(font)
        self.p_three.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);\n"
"border-radius: 22px;")
        self.p_three.setObjectName("p_three")
        self.p_zero = QtWidgets.QPushButton(self.frame_buttons)
        self.p_zero.setGeometry(QtCore.QRect(120, 250, 47, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.p_zero.setFont(font)
        self.p_zero.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);\n"
"border-radius: 22px;")
        self.p_zero.setObjectName("p_zero")
        self.p_two = QtWidgets.QPushButton(self.frame_buttons)
        self.p_two.setGeometry(QtCore.QRect(120, 200, 47, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.p_two.setFont(font)
        self.p_two.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);\n"
"border-radius: 22px;")
        self.p_two.setObjectName("p_two")
        self.p_eight = QtWidgets.QPushButton(self.frame_buttons)
        self.p_eight.setGeometry(QtCore.QRect(120, 100, 47, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.p_eight.setFont(font)
        self.p_eight.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);\n"
"border-radius: 22px;")
        self.p_eight.setObjectName("p_eight")
        self.p_five = QtWidgets.QPushButton(self.frame_buttons)
        self.p_five.setGeometry(QtCore.QRect(120, 150, 47, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.p_five.setFont(font)
        self.p_five.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);\n"
"border-radius: 22px;")
        self.p_five.setObjectName("p_five")
        self.p_seven = QtWidgets.QPushButton(self.frame_buttons)
        self.p_seven.setGeometry(QtCore.QRect(60, 100, 47, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.p_seven.setFont(font)
        self.p_seven.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);\n"
"border-radius: 22px;")
        self.p_seven.setObjectName("p_seven")
        self.p_plus_minus = QtWidgets.QPushButton(self.frame_buttons)
        self.p_plus_minus.setGeometry(QtCore.QRect(60, 250, 47, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.p_plus_minus.setFont(font)
        self.p_plus_minus.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);\n"
"border-radius: 22px;")
        self.p_plus_minus.setObjectName("p_plus_minus")
        self.p_multiply = QtWidgets.QPushButton(self.frame_buttons)
        self.p_multiply.setGeometry(QtCore.QRect(240, 100, 81, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.p_multiply.setFont(font)
        self.p_multiply.setStyleSheet("color: rgb(120, 120, 120);\n"
"border-radius: 22px;\n"
"background-color: rgb(255, 216, 97);\n"
"")
        self.p_multiply.setObjectName("p_multiply")
        self.p_divide = QtWidgets.QPushButton(self.frame_buttons)
        self.p_divide.setGeometry(QtCore.QRect(240, 50, 81, 45))
        self.p_divide.setMinimumSize(QtCore.QSize(51, 45))
        self.p_divide.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.p_divide.setFont(font)
        self.p_divide.setStyleSheet("color: rgb(120, 120, 120);\n"
"border-radius: 22px;\n"
"background-color: rgb(255, 216, 97);\n"
"")
        self.p_divide.setObjectName("p_divide")
        self.p_six = QtWidgets.QPushButton(self.frame_buttons)
        self.p_six.setGeometry(QtCore.QRect(180, 150, 47, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.p_six.setFont(font)
        self.p_six.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);\n"
"border-radius: 22px;")
        self.p_six.setObjectName("p_six")
        self.p_four = QtWidgets.QPushButton(self.frame_buttons)
        self.p_four.setGeometry(QtCore.QRect(60, 150, 47, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.p_four.setFont(font)
        self.p_four.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);\n"
"border-radius: 22px;")
        self.p_four.setObjectName("p_four")
        self.p_plus = QtWidgets.QPushButton(self.frame_buttons)
        self.p_plus.setGeometry(QtCore.QRect(240, 200, 81, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.p_plus.setFont(font)
        self.p_plus.setStyleSheet("color: rgb(120, 120, 120);\n"
"border-radius: 22px;\n"
"background-color: rgb(255, 216, 97);\n"
"")
        self.p_plus.setObjectName("p_plus")
        self.p_equal = QtWidgets.QPushButton(self.frame_buttons)
        self.p_equal.setGeometry(QtCore.QRect(240, 250, 81, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.p_equal.setFont(font)
        self.p_equal.setStyleSheet("color: rgb(120, 120, 120);\n"
"border-radius: 22px;\n"
"background-color: rgb(255, 216, 97);\n"
"")
        self.p_equal.setObjectName("p_equal")
        self.p_nine = QtWidgets.QPushButton(self.frame_buttons)
        self.p_nine.setGeometry(QtCore.QRect(180, 100, 47, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.p_nine.setFont(font)
        self.p_nine.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);\n"
"border-radius: 22px;")
        self.p_nine.setObjectName("p_nine")
        self.p_minus = QtWidgets.QPushButton(self.frame_buttons)
        self.p_minus.setGeometry(QtCore.QRect(240, 150, 81, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.p_minus.setFont(font)
        self.p_minus.setStyleSheet("color: rgb(120, 120, 120);\n"
"border-radius: 22px;\n"
"background-color: rgb(255, 216, 97);\n"
"")
        self.p_minus.setObjectName("p_minus")
        self.p_one = QtWidgets.QPushButton(self.frame_buttons)
        self.p_one.setGeometry(QtCore.QRect(60, 200, 47, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.p_one.setFont(font)
        self.p_one.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(193, 193, 193);\n"
"border-radius: 22px;")
        self.p_one.setObjectName("p_one")
        self.p_ce = QtWidgets.QPushButton(self.frame_buttons)
        self.p_ce.setGeometry(QtCore.QRect(180, 0, 47, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p_ce.setFont(font)
        self.p_ce.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(232, 232, 232);\n"
"border-radius: 22px;")
        self.p_ce.setObjectName("p_ce")
        self.p_back = QtWidgets.QPushButton(self.frame_buttons)
        self.p_back.setGeometry(QtCore.QRect(240, 0, 81, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.p_back.setFont(font)
        self.p_back.setStyleSheet("color: rgb(120, 120, 120);\n"
"border-radius: 22px;\n"
"background-color: rgb(255, 216, 97);\n"
"")
        self.p_back.setObjectName("p_back")
        self.p_close_bracket = QtWidgets.QPushButton(self.frame_buttons)
        self.p_close_bracket.setGeometry(QtCore.QRect(120, 50, 47, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p_close_bracket.setFont(font)
        self.p_close_bracket.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(232, 232, 232);\n"
"border-radius: 22px;")
        self.p_close_bracket.setObjectName("p_close_bracket")
        self.p_open_bracket = QtWidgets.QPushButton(self.frame_buttons)
        self.p_open_bracket.setGeometry(QtCore.QRect(60, 50, 47, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p_open_bracket.setFont(font)
        self.p_open_bracket.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(232, 232, 232);\n"
"border-radius: 22px;")
        self.p_open_bracket.setObjectName("p_open_bracket")
        self.p_d = QtWidgets.QPushButton(self.frame_buttons)
        self.p_d.setGeometry(QtCore.QRect(0, 150, 47, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p_d.setFont(font)
        self.p_d.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(232, 232, 232);\n"
"border-radius: 22px;")
        self.p_d.setObjectName("p_d")
        self.p_c = QtWidgets.QPushButton(self.frame_buttons)
        self.p_c.setGeometry(QtCore.QRect(0, 100, 47, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p_c.setFont(font)
        self.p_c.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(232, 232, 232);\n"
"border-radius: 22px;")
        self.p_c.setObjectName("p_c")
        self.p_f = QtWidgets.QPushButton(self.frame_buttons)
        self.p_f.setGeometry(QtCore.QRect(0, 250, 47, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p_f.setFont(font)
        self.p_f.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(232, 232, 232);\n"
"border-radius: 22px;")
        self.p_f.setObjectName("p_f")
        self.p_e = QtWidgets.QPushButton(self.frame_buttons)
        self.p_e.setGeometry(QtCore.QRect(0, 200, 47, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p_e.setFont(font)
        self.p_e.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(232, 232, 232);\n"
"border-radius: 22px;")
        self.p_e.setObjectName("p_e")
        self.p_a = QtWidgets.QPushButton(self.frame_buttons)
        self.p_a.setGeometry(QtCore.QRect(0, 0, 47, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p_a.setFont(font)
        self.p_a.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(232, 232, 232);\n"
"border-radius: 22px;")
        self.p_a.setObjectName("p_a")
        self.p_b = QtWidgets.QPushButton(self.frame_buttons)
        self.p_b.setGeometry(QtCore.QRect(0, 50, 47, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p_b.setFont(font)
        self.p_b.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(232, 232, 232);\n"
"border-radius: 22px;")
        self.p_b.setObjectName("p_b")
        self.p_per = QtWidgets.QPushButton(self.frame_buttons)
        self.p_per.setGeometry(QtCore.QRect(180, 50, 47, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p_per.setFont(font)
        self.p_per.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(232, 232, 232);\n"
"border-radius: 22px;")
        self.p_per.setObjectName("p_per")
        self.p_lsh = QtWidgets.QPushButton(self.frame_buttons)
        self.p_lsh.setGeometry(QtCore.QRect(60, 0, 47, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p_lsh.setFont(font)
        self.p_lsh.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(232, 232, 232);\n"
"border-radius: 22px;")
        self.p_lsh.setObjectName("p_lsh")
        self.p_rsh = QtWidgets.QPushButton(self.frame_buttons)
        self.p_rsh.setGeometry(QtCore.QRect(120, 0, 47, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p_rsh.setFont(font)
        self.p_rsh.setStyleSheet("color: rgb(120, 120, 120);\n"
"background-color: rgb(232, 232, 232);\n"
"border-radius: 22px;")
        self.p_rsh.setObjectName("p_rsh")
        self.frame_calculations_display = QtWidgets.QFrame(self.frame)
        self.frame_calculations_display.setGeometry(QtCore.QRect(10, 40, 321, 71))
        self.frame_calculations_display.setStyleSheet("")
        self.frame_calculations_display.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_calculations_display.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_calculations_display.setObjectName("frame_calculations_display")
        self.p_label_2 = QtWidgets.QLabel(self.frame_calculations_display)
        self.p_label_2.setGeometry(QtCore.QRect(0, 30, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.p_label_2.setFont(font)
        self.p_label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.p_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.p_label_2.setStyleSheet("color: rgb(117, 117, 117);")

        self.p_label_2.setObjectName("p_label_2")
        self.p_label_3 = QtWidgets.QLabel(self.frame_calculations_display)
        self.p_label_3.setGeometry(QtCore.QRect(0, 0, 321, 20))
        self.p_label_3.setMaximumSize(QtCore.QSize(100000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.p_label_3.setFont(font)
        self.p_label_3.setStyleSheet("color: rgb(117, 117, 117);")
        self.p_label_3.setText("")
        self.p_label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.p_label_3.setObjectName("p_label_3")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 10, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(117, 117, 117);")
        self.label.setObjectName("label")
        self.p_label_bin = QtWidgets.QLabel(self.frame)
        self.p_label_bin.setGeometry(QtCore.QRect(10, 205, 51, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.p_label_bin.setFont(font)
        self.p_label_bin.setStyleSheet("color: rgb(117, 117, 117);")
        self.p_label_bin.setObjectName("p_label_bin")
        self.p_label_oct = QtWidgets.QLabel(self.frame)
        self.p_label_oct.setGeometry(QtCore.QRect(10, 180, 51, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.p_label_oct.setFont(font)
        self.p_label_oct.setStyleSheet("color: rgb(117, 117, 117);")

        self.p_label_oct.setObjectName("p_label_oct")
        self.p_label_dec = QtWidgets.QLabel(self.frame)
        self.p_label_dec.setGeometry(QtCore.QRect(10, 150, 51, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.p_label_dec.setFont(font)
        self.p_label_dec.setStyleSheet("color: rgb(117, 117, 117);")

        self.p_label_dec.setObjectName("p_label_dec")
        self.p_label_hex = QtWidgets.QLabel(self.frame)
        self.p_label_hex.setGeometry(QtCore.QRect(10, 120, 51, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.p_label_hex.setFont(font)
        self.p_label_hex.setStyleSheet("color: rgb(117, 117, 117);")

        self.p_label_hex.setObjectName("p_label_hex")
        self.p_label_hex_val = QtWidgets.QLabel(self.frame)
        self.p_label_hex_val.setGeometry(QtCore.QRect(60, 120, 281, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.p_label_hex_val.setFont(font)
        self.p_label_hex_val.setStyleSheet("color: rgb(117, 117, 117);")

        self.p_label_hex_val.setObjectName("p_label_hex_val")
        self.p_label_dec_val = QtWidgets.QLabel(self.frame)
        self.p_label_dec_val.setGeometry(QtCore.QRect(60, 150, 281, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.p_label_dec_val.setFont(font)
        self.p_label_dec_val.setStyleSheet("color: rgb(117, 117, 117);")

        self.p_label_dec_val.setObjectName("p_label_dec_val")
        self.p_label_oct_val = QtWidgets.QLabel(self.frame)
        self.p_label_oct_val.setGeometry(QtCore.QRect(60, 180, 281, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.p_label_oct_val.setFont(font)
        self.p_label_oct_val.setStyleSheet("color: rgb(117, 117, 117);")

        self.p_label_oct_val.setObjectName("p_label_oct_val")
        self.p_label_bin_val = QtWidgets.QLabel(self.frame)
        self.p_label_bin_val.setGeometry(QtCore.QRect(60, 205, 281, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.p_label_bin_val.setFont(font)
        self.p_label_bin_val.setStyleSheet("color: rgb(117, 117, 117);")

        self.p_label_bin_val.setObjectName("p_label_bin_val")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 339, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuOption = QtWidgets.QMenu(self.menuBar)
        self.menuOption.setStyleSheet("")
        self.menuOption.setTitle("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../images/text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuOption.setIcon(icon1)
        self.menuOption.setObjectName("menuOption")
        self.menuCalculator = QtWidgets.QMenu(self.menuOption)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../images/calculator(3).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuCalculator.setIcon(icon2)
        self.menuCalculator.setObjectName("menuCalculator")
        self.menuConverter = QtWidgets.QMenu(self.menuOption)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../images/recycle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuConverter.setIcon(icon3)
        self.menuConverter.setObjectName("menuConverter")

        MainWindow.setMenuBar(self.menuBar)
        self.actionDark = QtWidgets.QAction(MainWindow)
        self.actionDark.setObjectName("actionDark")
        self.actionLight = QtWidgets.QAction(MainWindow)
        self.actionLight.setObjectName("actionLight")
        self.actionSetting = QtWidgets.QAction(MainWindow)
        self.actionSetting.setObjectName("actionSetting")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../images/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon4)
        self.actionExit.setObjectName("actionExit")
        self.actionStandard = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../images/calculator.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStandard.setIcon(icon5)
        self.actionStandard.setObjectName("actionStandard")
        self.actionScientific = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../images/microscope.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionScientific.setIcon(icon6)
        self.actionScientific.setObjectName("actionScientific")
        self.actionProgrammer = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../images/code.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionProgrammer.setIcon(icon7)
        self.actionProgrammer.setObjectName("actionProgrammer")
        self.actionDate_Calculation = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../images/calendar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDate_Calculation.setIcon(icon8)
        self.actionDate_Calculation.setObjectName("actionDate_Calculation")
        self.actionCurrency = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../images/money.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCurrency.setIcon(icon9)
        self.actionCurrency.setObjectName("actionCurrency")
        self.actionVolume = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../images/shapes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVolume.setIcon(icon10)
        self.actionVolume.setObjectName("actionVolume")
        self.actionLength = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../images/ruler.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLength.setIcon(icon11)
        self.actionLength.setObjectName("actionLength")
        self.actionWeight_and_Mass = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("../images/weighing-scale.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionWeight_and_Mass.setIcon(icon12)
        self.actionWeight_and_Mass.setObjectName("actionWeight_and_Mass")
        self.actionTemperature = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("../images/temperature.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTemperature.setIcon(icon13)
        self.actionTemperature.setObjectName("actionTemperature")
        self.actionEnergy = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("../images/fire.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEnergy.setIcon(icon14)
        self.actionEnergy.setObjectName("actionEnergy")
        self.actionArea = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("../images/area.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionArea.setIcon(icon15)
        self.actionArea.setObjectName("actionArea")
        self.actionSpeed = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("../images/fast.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSpeed.setIcon(icon16)
        self.actionSpeed.setObjectName("actionSpeed")
        self.actionTime = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("../images/clock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTime.setIcon(icon17)
        self.actionTime.setObjectName("actionTime")
        self.actionPower = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("../images/energy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPower.setIcon(icon18)
        self.actionPower.setObjectName("actionPower")
        self.actionData = QtWidgets.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("../images/statistics.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionData.setIcon(icon19)
        self.actionData.setObjectName("actionData")
        self.actionPressure = QtWidgets.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("../images/indicator.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPressure.setIcon(icon20)
        self.actionPressure.setObjectName("actionPressure")
        self.actionAngle = QtWidgets.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("../images/angle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAngle.setIcon(icon21)
        self.actionAngle.setObjectName("actionAngle")

        self.actionDark_ = QtWidgets.QAction(MainWindow)
        self.actionDark_.setObjectName("actionDark_")
        self.actionLight_ = QtWidgets.QAction(MainWindow)
        self.actionLight_.setObjectName("actionLight_")
        self.menuCalculator.addAction(self.actionStandard)
        self.menuCalculator.addAction(self.actionScientific)
        self.menuCalculator.addAction(self.actionProgrammer)
        self.menuCalculator.addAction(self.actionDate_Calculation)
        self.menuConverter.addAction(self.actionVolume)
        self.menuConverter.addAction(self.actionLength)
        self.menuConverter.addAction(self.actionWeight_and_Mass)
        self.menuConverter.addAction(self.actionTemperature)
        self.menuConverter.addAction(self.actionEnergy)
        self.menuConverter.addAction(self.actionArea)
        self.menuConverter.addAction(self.actionSpeed)
        self.menuConverter.addAction(self.actionTime)
        self.menuConverter.addAction(self.actionPower)
        self.menuConverter.addAction(self.actionData)
        self.menuConverter.addAction(self.actionPressure)
        self.menuConverter.addAction(self.actionAngle)
        self.menuOption.addAction(self.menuCalculator.menuAction())
        self.menuOption.addAction(self.menuConverter.menuAction())
        self.menuOption.addSeparator()
        self.menuOption.addAction(self.actionExit)
        self.menuBar.addAction(self.menuOption.menuAction())


        self.p_retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def p_retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.p_point.setText(_translate("MainWindow", "."))
        self.p_three.setText(_translate("MainWindow", "3"))
        self.p_zero.setText(_translate("MainWindow", "0"))
        self.p_two.setText(_translate("MainWindow", "2"))
        self.p_eight.setText(_translate("MainWindow", "8"))
        self.p_five.setText(_translate("MainWindow", "5"))
        self.p_seven.setText(_translate("MainWindow", "7"))
        self.p_plus_minus.setText(_translate("MainWindow", "+/-"))
        self.p_multiply.setToolTip(_translate("MainWindow", "Multiply"))
        self.p_multiply.setText(_translate("MainWindow", "X"))
        self.p_divide.setToolTip(_translate("MainWindow", "Divide"))
        self.p_divide.setText(_translate("MainWindow", "/"))
        self.p_six.setText(_translate("MainWindow", "6"))
        self.p_four.setText(_translate("MainWindow", "4"))
        self.p_plus.setToolTip(_translate("MainWindow", "Plus"))
        self.p_plus.setText(_translate("MainWindow", "+"))
        self.p_equal.setText(_translate("MainWindow", "="))
        self.p_nine.setText(_translate("MainWindow", "9"))
        self.p_minus.setToolTip(_translate("MainWindow", "Subtract"))
        self.p_minus.setText(_translate("MainWindow", "-"))
        self.p_one.setText(_translate("MainWindow", "1"))
        self.p_ce.setToolTip(_translate("MainWindow", "Clear"))
        self.p_ce.setText(_translate("MainWindow", "CE"))
        self.p_back.setToolTip(_translate("MainWindow", "Remove/Back"))
        self.p_back.setText(_translate("MainWindow", "<"))
        self.p_close_bracket.setText(_translate("MainWindow", ")"))
        self.p_open_bracket.setText(_translate("MainWindow", "("))
        self.p_d.setText(_translate("MainWindow", "D"))
        self.p_c.setText(_translate("MainWindow", "C"))
        self.p_f.setText(_translate("MainWindow", "F"))
        self.p_e.setText(_translate("MainWindow", "E"))
        self.p_a.setToolTip(_translate("MainWindow", "Square"))
        self.p_a.setText(_translate("MainWindow", "A"))
        self.p_b.setToolTip(_translate("MainWindow", "Square root"))
        self.p_b.setText(_translate("MainWindow", "B"))
        self.p_per.setText(_translate("MainWindow", "%"))
        self.p_lsh.setText(_translate("MainWindow", "<<"))
        self.p_rsh.setText(_translate("MainWindow", ">>"))
        self.p_label_2.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "Programmer"))
        self.p_label_bin.setText(_translate("MainWindow", "BIN"))
        self.p_label_oct.setText(_translate("MainWindow", "OCT"))
        self.p_label_dec.setText(_translate("MainWindow", "DEC"))
        self.p_label_hex.setText(_translate("MainWindow", "HEX"))
        self.p_label_hex_val.setText(_translate("MainWindow", "0"))
        self.p_label_dec_val.setText(_translate("MainWindow", "0"))
        self.p_label_oct_val.setText(_translate("MainWindow", "0"))
        self.p_label_bin_val.setText(_translate("MainWindow", "0"))
        self.menuCalculator.setTitle(_translate("MainWindow", "Calculator"))
        self.menuConverter.setTitle(_translate("MainWindow", "Converter"))
        self.actionDark.setText(_translate("MainWindow", "Dark"))
        self.actionLight.setText(_translate("MainWindow", "Light"))
        self.actionSetting.setText(_translate("MainWindow", "Setting"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionStandard.setText(_translate("MainWindow", "Standard"))
        self.actionScientific.setText(_translate("MainWindow", "Scientific"))
        self.actionProgrammer.setText(_translate("MainWindow", "Programmer"))
        self.actionDate_Calculation.setText(_translate("MainWindow", "Date Calculation"))
        self.actionCurrency.setText(_translate("MainWindow", "Currency"))
        self.actionVolume.setText(_translate("MainWindow", "Volume"))
        self.actionLength.setText(_translate("MainWindow", "Length"))
        self.actionWeight_and_Mass.setText(_translate("MainWindow", "Weight and Mass"))
        self.actionTemperature.setText(_translate("MainWindow", "Temperature"))
        self.actionEnergy.setText(_translate("MainWindow", "Energy"))
        self.actionArea.setText(_translate("MainWindow", "Area"))
        self.actionSpeed.setText(_translate("MainWindow", "Speed"))
        self.actionTime.setText(_translate("MainWindow", "Time"))
        self.actionPower.setText(_translate("MainWindow", "Power"))
        self.actionData.setText(_translate("MainWindow", "Data"))
        self.actionPressure.setText(_translate("MainWindow", "Pressure"))
        self.actionAngle.setText(_translate("MainWindow", "Angle"))
        self.actionDark_.setText(_translate("MainWindow", "Dark"))
        self.actionLight_.setText(_translate("MainWindow", "Light"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_Programmer()
    ui.setupUiProgrammer(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
